### PR TITLE
vertical alignment added closes macCesar/tailwind-tss-color-generator#5

### PR DESCRIPTION
**Pull request by caspahouzer**

### CODE REVIEW

**Comment by macCesar** [comment]
Thanks for the PR!!!

**Comment by macCesar** [comment]
@caspahouzer ... I'm going to refactor your pull request.

Stay tuned!!

**Comment by macCesar** [comment]
The purpose of **tailwind.css** is to have the same names as **tailwind.css** and match them to the properties of Appcelerator as close as possible.

**Comment by caspahouzer** [comment]
Understand. Next PR will come with exact tailwind.css matches

**Comment by macCesar** [comment]
Excellent!!

Thanks!!

**Pull request merged**
